[package]
name = "streamlette"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
stdcode = "0.1.10"
tmelcrypt = "0.2.4"
